/*
** DON'T EDIT THIS FILE **
It's been generated by Zapatos (v5.0.0), and is liable to be overwritten

Zapatos: https://jawj.github.io/zapatos/
Copyright (C) 2020 - 2021 George MacKerron
Released under the MIT licence: see LICENCE file
*/

declare module 'zapatos/schema' {

  import type * as db from 'zapatos/db';

  // got a type error on schemaVersionCanary below? update by running `npx zapatos`
  export interface schemaVersionCanary extends db.SchemaVersionCanary { version: 103 }

  /* === schema: public === */

  /* --- enums --- */


  /* --- tables --- */

  /**
   * **clubs**
   * - Table in database
   */
  export namespace clubs {
    export type Table = 'clubs';
    export interface Selectable {
      /**
      * **clubs.clubid**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      clubid: number;
      /**
      * **clubs.clubname**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      clubname: string;
      /**
      * **clubs.amount**
      * - `float4` in database
      * - `NOT NULL`, default: `0`
      */
      amount: number;
    }
    export interface JSONSelectable {
      /**
      * **clubs.clubid**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      clubid: number;
      /**
      * **clubs.clubname**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      clubname: string;
      /**
      * **clubs.amount**
      * - `float4` in database
      * - `NOT NULL`, default: `0`
      */
      amount: number;
    }
    export interface Whereable {
      /**
      * **clubs.clubid**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      clubid?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **clubs.clubname**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      clubname?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **clubs.amount**
      * - `float4` in database
      * - `NOT NULL`, default: `0`
      */
      amount?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **clubs.clubid**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      clubid: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **clubs.clubname**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      clubname: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **clubs.amount**
      * - `float4` in database
      * - `NOT NULL`, default: `0`
      */
      amount?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **clubs.clubid**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      clubid?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **clubs.clubname**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      clubname?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **clubs.amount**
      * - `float4` in database
      * - `NOT NULL`, default: `0`
      */
      amount?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.DefaultType | db.SQLFragment>;
    }
    export type UniqueIndex = 'clubs_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = db.GenericSQLExpression | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Table | Whereable | Column;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /**
   * **execs**
   * - Table in database
   */
  export namespace execs {
    export type Table = 'execs';
    export interface Selectable {
      /**
      * **execs.ccid**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      ccid: string;
      /**
      * **execs.password**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      password: string;
      /**
      * **execs.clubid**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      clubid: number;
    }
    export interface JSONSelectable {
      /**
      * **execs.ccid**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      ccid: string;
      /**
      * **execs.password**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      password: string;
      /**
      * **execs.clubid**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      clubid: number;
    }
    export interface Whereable {
      /**
      * **execs.ccid**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      ccid?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **execs.password**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      password?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **execs.clubid**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      clubid?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **execs.ccid**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      ccid: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **execs.password**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      password: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **execs.clubid**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      clubid: number | db.Parameter<number> | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **execs.ccid**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      ccid?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **execs.password**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      password?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **execs.clubid**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      clubid?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
    }
    export type UniqueIndex = 'execs_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = db.GenericSQLExpression | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Table | Whereable | Column;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /**
   * **transactions**
   * - Table in database
   */
  export namespace transactions {
    export type Table = 'transactions';
    export interface Selectable {
      /**
      * **transactions.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id: string;
      /**
      * **transactions.clubid**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      clubid: number;
      /**
      * **transactions.ccid**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      ccid: string;
      /**
      * **transactions.created_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      created_at: Date;
      /**
      * **transactions.amount**
      * - `float4` in database
      * - `NOT NULL`, no default
      */
      amount: number;
    }
    export interface JSONSelectable {
      /**
      * **transactions.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id: string;
      /**
      * **transactions.clubid**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      clubid: number;
      /**
      * **transactions.ccid**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      ccid: string;
      /**
      * **transactions.created_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      created_at: db.TimestampTzString;
      /**
      * **transactions.amount**
      * - `float4` in database
      * - `NOT NULL`, no default
      */
      amount: number;
    }
    export interface Whereable {
      /**
      * **transactions.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **transactions.clubid**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      clubid?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **transactions.ccid**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      ccid?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **transactions.created_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      created_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn>;
      /**
      * **transactions.amount**
      * - `float4` in database
      * - `NOT NULL`, no default
      */
      amount?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **transactions.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment;
      /**
      * **transactions.clubid**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      clubid: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **transactions.ccid**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      ccid: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **transactions.created_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      created_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment;
      /**
      * **transactions.amount**
      * - `float4` in database
      * - `NOT NULL`, no default
      */
      amount: number | db.Parameter<number> | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **transactions.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.DefaultType | db.SQLFragment>;
      /**
      * **transactions.clubid**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      clubid?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **transactions.ccid**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      ccid?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **transactions.created_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      created_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment>;
      /**
      * **transactions.amount**
      * - `float4` in database
      * - `NOT NULL`, no default
      */
      amount?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
    }
    export type UniqueIndex = 'transactions_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = db.GenericSQLExpression | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Table | Whereable | Column;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /**
   * **users**
   * - Table in database
   */
  export namespace users {
    export type Table = 'users';
    export interface Selectable {
      /**
      * **users.ccid**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      ccid: string;
      /**
      * **users.isexec**
      * - `bool` in database
      * - `NOT NULL`, default: `false`
      */
      isexec: boolean;
      /**
      * **users.full_name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      full_name: string;
      /**
      * **users.foip**
      * - `bool` in database
      * - `NOT NULL`, default: `false`
      */
      foip: boolean;
      /**
      * **users.balance**
      * - `float4` in database
      * - `NOT NULL`, default: `0`
      */
      balance: number;
    }
    export interface JSONSelectable {
      /**
      * **users.ccid**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      ccid: string;
      /**
      * **users.isexec**
      * - `bool` in database
      * - `NOT NULL`, default: `false`
      */
      isexec: boolean;
      /**
      * **users.full_name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      full_name: string;
      /**
      * **users.foip**
      * - `bool` in database
      * - `NOT NULL`, default: `false`
      */
      foip: boolean;
      /**
      * **users.balance**
      * - `float4` in database
      * - `NOT NULL`, default: `0`
      */
      balance: number;
    }
    export interface Whereable {
      /**
      * **users.ccid**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      ccid?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **users.isexec**
      * - `bool` in database
      * - `NOT NULL`, default: `false`
      */
      isexec?: boolean | db.Parameter<boolean> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, boolean | db.Parameter<boolean> | db.SQLFragment | db.ParentColumn>;
      /**
      * **users.full_name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      full_name?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **users.foip**
      * - `bool` in database
      * - `NOT NULL`, default: `false`
      */
      foip?: boolean | db.Parameter<boolean> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, boolean | db.Parameter<boolean> | db.SQLFragment | db.ParentColumn>;
      /**
      * **users.balance**
      * - `float4` in database
      * - `NOT NULL`, default: `0`
      */
      balance?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **users.ccid**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      ccid: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **users.isexec**
      * - `bool` in database
      * - `NOT NULL`, default: `false`
      */
      isexec?: boolean | db.Parameter<boolean> | db.DefaultType | db.SQLFragment;
      /**
      * **users.full_name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      full_name: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **users.foip**
      * - `bool` in database
      * - `NOT NULL`, default: `false`
      */
      foip?: boolean | db.Parameter<boolean> | db.DefaultType | db.SQLFragment;
      /**
      * **users.balance**
      * - `float4` in database
      * - `NOT NULL`, default: `0`
      */
      balance?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **users.ccid**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      ccid?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **users.isexec**
      * - `bool` in database
      * - `NOT NULL`, default: `false`
      */
      isexec?: boolean | db.Parameter<boolean> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, boolean | db.Parameter<boolean> | db.DefaultType | db.SQLFragment>;
      /**
      * **users.full_name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      full_name?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **users.foip**
      * - `bool` in database
      * - `NOT NULL`, default: `false`
      */
      foip?: boolean | db.Parameter<boolean> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, boolean | db.Parameter<boolean> | db.DefaultType | db.SQLFragment>;
      /**
      * **users.balance**
      * - `float4` in database
      * - `NOT NULL`, default: `0`
      */
      balance?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.DefaultType | db.SQLFragment>;
    }
    export type UniqueIndex = 'users_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = db.GenericSQLExpression | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Table | Whereable | Column;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /* === cross-table types === */

  export type Table = clubs.Table | execs.Table | transactions.Table | users.Table;
  export type Selectable = clubs.Selectable | execs.Selectable | transactions.Selectable | users.Selectable;
  export type JSONSelectable = clubs.JSONSelectable | execs.JSONSelectable | transactions.JSONSelectable | users.JSONSelectable;
  export type Whereable = clubs.Whereable | execs.Whereable | transactions.Whereable | users.Whereable;
  export type Insertable = clubs.Insertable | execs.Insertable | transactions.Insertable | users.Insertable;
  export type Updatable = clubs.Updatable | execs.Updatable | transactions.Updatable | users.Updatable;
  export type UniqueIndex = clubs.UniqueIndex | execs.UniqueIndex | transactions.UniqueIndex | users.UniqueIndex;
  export type Column = clubs.Column | execs.Column | transactions.Column | users.Column;
  export type AllBaseTables = [clubs.Table, execs.Table, transactions.Table, users.Table];
  export type AllForeignTables = [];
  export type AllViews = [];
  export type AllMaterializedViews = [];
  export type AllTablesAndViews = [clubs.Table, execs.Table, transactions.Table, users.Table];


  export type SelectableForTable<T extends Table> = {
    clubs: clubs.Selectable;
    execs: execs.Selectable;
    transactions: transactions.Selectable;
    users: users.Selectable;
  }[T];

  export type JSONSelectableForTable<T extends Table> = {
    clubs: clubs.JSONSelectable;
    execs: execs.JSONSelectable;
    transactions: transactions.JSONSelectable;
    users: users.JSONSelectable;
  }[T];

  export type WhereableForTable<T extends Table> = {
    clubs: clubs.Whereable;
    execs: execs.Whereable;
    transactions: transactions.Whereable;
    users: users.Whereable;
  }[T];

  export type InsertableForTable<T extends Table> = {
    clubs: clubs.Insertable;
    execs: execs.Insertable;
    transactions: transactions.Insertable;
    users: users.Insertable;
  }[T];

  export type UpdatableForTable<T extends Table> = {
    clubs: clubs.Updatable;
    execs: execs.Updatable;
    transactions: transactions.Updatable;
    users: users.Updatable;
  }[T];

  export type UniqueIndexForTable<T extends Table> = {
    clubs: clubs.UniqueIndex;
    execs: execs.UniqueIndex;
    transactions: transactions.UniqueIndex;
    users: users.UniqueIndex;
  }[T];

  export type ColumnForTable<T extends Table> = {
    clubs: clubs.Column;
    execs: execs.Column;
    transactions: transactions.Column;
    users: users.Column;
  }[T];

  export type SQLForTable<T extends Table> = {
    clubs: clubs.SQL;
    execs: execs.SQL;
    transactions: transactions.SQL;
    users: users.SQL;
  }[T];

}
